---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    {{- if .Values.tls.enabled }}
    cert-manager.io/cluster-issuer: production
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "name" . }}
            port:
              number: 8080
    host: {{ .Values.ingress.host }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ template "name" . }}
  {{- end }}
